choco install 7zip.install
choco install adobereader
choco install androidstudio
choco install atom
choco install autohotkey.install
choco install ccleaner
choco install filezilla
choco install firefox
choco install foxitreader
choco install git.install
choco install github
choco install gnuplot
choco install google-chrome-x64
choco install graphviz
choco install itunes
choco install javaruntime
choco install octave
choco install powershell -pre
choco install r.studio
choco install skype
choco install sourcetree
choco install spf13-vim
choco install spotify 
choco install steam
choco install sublimetext3
choco install teamviewer
choco install texmaker
choco install unity
choco install vim
choco install visualstudiocode 
choco install vlc
choco install wox